# -*- coding: utf-8 -*-
"""8bitdattobin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRs_g-E-GASjRzEXOyTtepxd0BzY2mSQ
"""

import struct
from google.colab import files
import re

# Upload the samples.dat file
print("Upload samples.dat file:")
uploaded = files.upload()

# Read the data from the uploaded file
file_name = next(iter(uploaded))
with open(file_name, "r") as f:  # Open as text file
    content = f.read()
    samples_str = re.split(r'[,\n]', content)

    # Convert the string values to integers
    samples = [int(sample.strip()) for sample in samples_str if sample.strip()]

print(f"Read {len(samples)} samples from {file_name}")

# Clamp values to signed 8-bit range (-128 to 127)
samples_8bit = [max(-128, min(127, s)) for s in samples]

# Convert to signed 8-bit and join all bytes
binary_data = b''.join(struct.pack('<b', sample) for sample in samples_8bit)

# Save to a file
with open("output_8bit.bin", "wb") as f:
    f.write(binary_data)

# Download the file
files.download("output_8bit.bin")